### ISSUE TITLE
list_insights() missing filter parameter

### ISSUE THREAD

**Issue by rosmo** [googleapis/python-recommender#71]
`list_insights()` call is missing filter parameter, even though it is supported by the API: https://cloud.google.com/recommender/docs/reference/rest/v1/projects.locations.insightTypes.insights/list

#### Environment details

  - OS type and version: OS X Big Sur
  - Python version: 3.8.2
  - pip version: 19.2.3
  - `google-cloud-recommender` version: 2.0.0

#### Steps to reproduce

  1. Try to pass a filter to list_insights()

#### Code example

```python
insights_response = client.list_insights(parent=full_parent, filter="stateInfo.state=ACTIVE")
```

#### Stack trace
```
TypeError: list_insights() got an unexpected keyword argument 'filter'
```

**Comment by munkhuushmgl** [comment]
I suggest you to use https://github.com/googleapis/python-recommender/blob/b4b9834c645db5dafc12db7a3a25fce64f960efd/google/cloud/recommender_v1/types/recommender_service.py#L42-L81


example:
```
    full_parent = f"projects/{project_id}/locations/{location}/recommenders/{recommender}"
    req = recommender.ListInsightsRequest(parent=full_parent, filter='state:"ACTIVE"')
    insights_response = client.list_insights(request=req)
```

**Comment by rosmo** [comment]
Thanks, I can use that. It's a bit strange though that `list_recommendations()` has it but `list_insights()` doesn't.
